import{strict as assert}from"node:assert";
import{readFileSync}from"node:fs";
const migration=readFileSync(new URL("../../supabase/migrations/20261002120000_rental_agreement_operational_amendments.sql",import.meta.url),"utf8");
const edge=readFileSync(new URL("../../supabase/functions/rental-agreement-amendments/index.ts",import.meta.url),"utf8");
const page=readFileSync(new URL("../pages/BookingRentalAgreement.tsx",import.meta.url),"utf8");
const admin=readFileSync(new URL("../components/admin/RentalAgreementAmendmentDialog.tsx",import.meta.url),"utf8");
const history=readFileSync(new URL("../components/admin/RentalAgreementHistoryDialog.tsx",import.meta.url),"utf8");
assert.match(migration,/CREATE TABLE public\.rental_agreement_revisions/);
assert.match(migration,/CREATE TRIGGER rental_agreement_revisions_immutable BEFORE UPDATE OR DELETE/);
assert.match(migration,/CREATE TABLE public\.rental_agreement_current_revisions/);
assert.match(migration,/UNIQUE \(booking_id, revision_number\)/);
assert.match(migration,/additional_authorized_drivers/);
assert.match(migration,/jsonb_array_elements\(names\)/);
assert.match(migration,/material:=\(_end_date IS DISTINCT FROM b\.end_date OR _dropoff_time IS DISTINCT FROM b\.dropoff_time\)/);
assert.match(migration,/Pending authenticated customer acceptance/);
assert.match(migration,/Authorized administrative\/operational amendment/);
assert.match(migration,/Only the booking Guest may accept this amendment/);
assert.match(migration,/source_proposal_id=p\.id/);
assert.doesNotMatch(migration,/UPDATE public\.booking_rental_agreements/i);
assert.doesNotMatch(migration,/DELETE FROM public\.booking_rental_agreements/i);
assert.doesNotMatch(edge,/stripe|paymentintent|checkout/i);
assert.match(edge,/Idempotency-Key.*rental-agreement-amendment/);
assert.match(edge,/record_rental_agreement_amendment_notification/);
assert.match(page,/Current Operative Agreement/);
assert.match(page,/Accept This Rental Agreement Amendment/);
assert.match(page,/does not create another booking or initiate a payment/);
assert.match(admin,/One full legal name per line/);
assert.match(admin,/requires_customer_acceptance/);
assert.match(history,/Download exact revision/);
assert.match(history,/Notification Evidence/);
assert.match(migration,/Alejandra Ponce Gutierrez/);
assert.match(migration,/34c278e8b3456c9f5255f71669f0e1373639d83d9922fce010a0d79c204d72e5|source_correction_id/);
console.log("PASS: append-only Rental Agreement amendment architecture and UI contracts");