import type { Vehicle } from "@/components/vehicles/VehicleCard";
import model3FsdImage from "@/assets/cars/model3-fsd.jpg";
import cybertruckImage from "@/assets/cars/cybertruck-fsd.png";
import cayenneSideImage from "@/assets/cars/cayenne-side.jpg";
import cayenneRearImage from "@/assets/cars/cayenne-rear.jpg";
import cayenneInteriorImage from "@/assets/cars/cayenne-interior.jpg";
import porscheTaycanImage from "@/assets/cars/porsche-taycan-green.jpg";
import porscheTaycanWheelImage from "@/assets/cars/porsche-taycan-wheel.jpg";

export interface HostProfile {
  name: string;
  bio: string;
  responseRate: string;
  responseTime: string;
  reviews: number;
  joinedDate: string;
  verified: boolean;
  superhost: boolean;
  stays: string;
  languages: string[];
  rating: number;
}

export const mockVehicles: Vehicle[] = [
  {
    id: "1",
    name: "2025 Tesla Cybertruck AWD",
    brand: "Tesla",
    category: "Electric Pickup",
    pricePerDay: 249,
    imageUrl: cybertruckImage,
    images: [cybertruckImage, porscheTaycanImage, cayenneSideImage],
    seats: 5,
    transmission: "automatic",
    fuelType: "Electric",
    available: true,
    host: "Zo",
    rating: 5.0,
    trips: 38,
    location: "Miami",
    verified: true,
    superhost: true,
    instantBook: true,
    airportDelivery: true,
    pickupArea: "2640 S Bayshore Dr, Miami, FL 33133",
    description: "A flagship electric pickup with elevated comfort, studio-grade cabin finishes, and exceptional daily utility.",
    features: ["Adaptive Air Suspension", "Full Self-Driving", "Vault Storage", "All-Wheel Drive", "Premium Interior"],
    addOns: [
      { key: "fsd", title: "⚡ Full Self-Driving (Supervised)", price: 175, description: "Enjoy Tesla's advanced driver assistance for longer highway stretches." },
      { key: "digital-key", title: "📱 Tesla Digital Key", price: 150, description: "Unlock and start the vehicle directly from your phone." },
    ],
    hostProfile: {
      name: "Zo",
      bio: "Former automotive designer focused on delivering luxury-grade EV handoffs and thoughtful hospitality for every trip.",
      responseRate: "99%",
      responseTime: "under 10 mins",
      reviews: 38,
      joinedDate: "Joined 2023",
      verified: true,
      superhost: true,
      stays: "1,200+ stays",
      languages: ["English", "Spanish"],
      rating: 5.0,
    },
  },
  {
    id: "2",
    name: "2025 Tesla Model 3",
    brand: "Tesla",
    category: "Electric Sedan",
    pricePerDay: 129,
    imageUrl: model3FsdImage,
    images: [model3FsdImage, cybertruckImage, cayenneInteriorImage],
    seats: 5,
    transmission: "automatic",
    fuelType: "Electric",
    available: true,
    host: "Miguel",
    rating: 4.98,
    trips: 21,
    location: "Miami",
    verified: true,
    superhost: false,
    instantBook: true,
    airportDelivery: false,
    pickupArea: "2640 S Bayshore Dr, Miami, FL 33133",
    description: "A polished everyday EV with intuitive tech, premium comfort, and effortless city access.",
    features: ["Autopilot", "Premium Audio", "Glass Roof", "Fast Charging", "Mobile App Access"],
    addOns: [
      { key: "fsd", title: "⚡ Full Self-Driving (Supervised)", price: 175, description: "Enjoy Tesla's advanced driver assistance for longer highway stretches." },
      { key: "digital-key", title: "📱 Tesla Digital Key", price: 150, description: "Unlock and start the vehicle directly from your phone." },
    ],
    hostProfile: {
      name: "Miguel",
      bio: "Miami local who loves pairing premium EVs with seamless arrival, flexible pickup, and attentive support.",
      responseRate: "97%",
      responseTime: "under 15 mins",
      reviews: 21,
      joinedDate: "Joined 2024",
      verified: true,
      superhost: false,
      stays: "780 stays",
      languages: ["English", "Spanish"],
      rating: 4.98,
    },
  },
  {
    id: "3",
    name: "2025 Rivian R1S",
    brand: "Rivian",
    category: "Electric SUV",
    pricePerDay: 219,
    imageUrl: cayenneSideImage,
    images: [cayenneSideImage, cayenneRearImage, cayenneInteriorImage],
    seats: 5,
    transmission: "automatic",
    fuelType: "Electric",
    available: true,
    host: "Jim",
    rating: 4.97,
    trips: 17,
    location: "Fort Lauderdale",
    verified: true,
    superhost: false,
    instantBook: true,
    airportDelivery: true,
    pickupArea: "2640 S Bayshore Dr, Miami, FL 33133",
    description: "An adventurous and refined SUV designed for premium weekend travel and relaxed family comfort.",
    features: ["Adventure Mode", "Panoramic Roof", "Premium Cabin", "Off-Road Capability", "Fast Charging"],
    hostProfile: {
      name: "Jim",
      bio: "Adventure host known for carefully curated road-trip setups and polished, hospitality-led vehicle access.",
      responseRate: "95%",
      responseTime: "under 20 mins",
      reviews: 17,
      joinedDate: "Joined 2022",
      verified: true,
      superhost: false,
      stays: "650 stays",
      languages: ["English"],
      rating: 4.97,
    },
  },
  {
    id: "4",
    name: "2025 Porsche Macan EV",
    brand: "Porsche",
    category: "Electric SUV",
    pricePerDay: 329,
    imageUrl: porscheTaycanImage,
    images: [porscheTaycanImage, porscheTaycanWheelImage, cayenneSideImage],
    seats: 5,
    transmission: "automatic",
    fuelType: "Electric",
    available: true,
    host: "Alex",
    rating: 4.9,
    trips: 0,
    location: "Homestead",
    verified: false,
    superhost: false,
    instantBook: false,
    airportDelivery: false,
    pickupArea: "2640 S Bayshore Dr, Miami, FL 33133",
    description: "A luxury performance SUV that blends Porsche poise with effortless EV range and modern comfort.",
    features: ["Sport Suspension", "Premium Audio", "Adaptive Cruise", "Panoramic Roof", "Launch Control"],
    hostProfile: {
      name: "Alex",
      bio: "New host bringing a boutique approach to luxury EV rentals with detailed preparation and elevated service.",
      responseRate: "92%",
      responseTime: "under 1 hour",
      reviews: 0,
      joinedDate: "Joined 2025",
      verified: false,
      superhost: false,
      stays: "New host",
      languages: ["English", "French"],
      rating: 4.9,
    },
  },
  {
    id: "5",
    name: "2025 Lucid Air Touring",
    brand: "Lucid",
    category: "Electric Sedan",
    pricePerDay: 269,
    imageUrl: model3FsdImage,
    images: [model3FsdImage, porscheTaycanImage, cybertruckImage],
    seats: 5,
    transmission: "automatic",
    fuelType: "Electric",
    available: true,
    host: "Juan Manuel",
    rating: 5.0,
    trips: 8,
    location: "Miami",
    verified: true,
    superhost: true,
    instantBook: true,
    airportDelivery: false,
    pickupArea: "2640 S Bayshore Dr, Miami, FL 33133",
    description: "An ultra-premium sedan with a tranquil cabin, exceptional range, and designer-level comfort.",
    features: ["Luxury Cabin", "Fast Charging", "Driver Assistance", "Massage Seats", "Adaptive Suspension"],
    hostProfile: {
      name: "Juan Manuel",
      bio: "Independent concierge host focused on effortless arrivals, detailed vehicle preparation, and elevated guest care.",
      responseRate: "100%",
      responseTime: "under 5 mins",
      reviews: 8,
      joinedDate: "Joined 2024",
      verified: true,
      superhost: true,
      stays: "360 stays",
      languages: ["English", "Spanish"],
      rating: 5.0,
    },
  },
  {
    id: "6",
    name: "Mercedes-Benz G580 EQ",
    brand: "Mercedes-Benz",
    category: "Electric SUV",
    pricePerDay: 389,
    imageUrl: cayenneSideImage,
    images: [cayenneSideImage, cayenneRearImage, cayenneInteriorImage],
    seats: 5,
    transmission: "automatic",
    fuelType: "Electric",
    available: true,
    host: "Elisa",
    rating: 4.99,
    trips: 12,
    location: "Miami",
    verified: true,
    superhost: false,
    instantBook: true,
    airportDelivery: true,
    pickupArea: "2640 S Bayshore Dr, Miami, FL 33133",
    description: "A high-luxury, full-size electric SUV with a quietly powerful presence and tailored hospitality.",
    features: ["Luxury Interior", "Adaptive Suspension", "Panoramic Roof", "Advanced Safety", "Premium Audio"],
    hostProfile: {
      name: "Elisa",
      bio: "Luxury host specializing in refined arrivals, concierge-style support, and polished, design-forward EV experiences.",
      responseRate: "98%",
      responseTime: "under 12 mins",
      reviews: 12,
      joinedDate: "Joined 2023",
      verified: true,
      superhost: false,
      stays: "540 stays",
      languages: ["English", "Italian"],
      rating: 4.99,
    },
  },
];

export const featuredVehicles = mockVehicles.slice(0, 4);
