export type Entry = { stable_key:string; entry_type:string; category:string; amount_cents:number; currency:string; effect:string; status:string; source:string; external_reference:string|null; description:string; occurred_at:string; metadata:Record<string,unknown> };
const uuid=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
export function authorizeReconciliation(authenticated:boolean,canAdmin:boolean){return !authenticated?{allowed:false,status:401}:!canAdmin?{allowed:false,status:403}:{allowed:true,status:200};}
export function parseReconciliationInput(body:unknown){const v=body as Record<string,unknown>|null;const allowed=["action","booking_id","reason","approved_ambiguous_payment_intent_ids","idempotency_key","proposal_fingerprint"];if(!v||Object.keys(v).some(k=>!allowed.includes(k))||!uuid.test(String(v.booking_id||"")))return null;const action=v.action==="prepare"||v.action==="confirm"?v.action:null;const source=Array.isArray(v.approved_ambiguous_payment_intent_ids)?v.approved_ambiguous_payment_intent_ids:[];const approved=source.filter(x=>typeof x==="string"&&/^pi_[A-Za-z0-9]+$/.test(x));if(!action||approved.length!==source.length)return null;return{action,bookingId:String(v.booking_id),reason:typeof v.reason==="string"?v.reason.trim():"",approved,idempotencyKey:typeof v.idempotency_key==="string"?v.idempotency_key.trim():"",proposalFingerprint:typeof v.proposal_fingerprint==="string"?v.proposal_fingerprint:""};}
const iso=(seconds:number|null|undefined,fallback:string)=>seconds?new Date(seconds*1000).toISOString():fallback;
const entry=(x:Entry)=>x;
export function buildReconciliationProposal(snapshot:any,before:any,approved:string[]){
  const observed=snapshot.observed_at;
  const entries:Entry[]=[];
  const oldTotal=Number(before.grand_total_cents||0);
  const components=[['rental_subtotal',Number(before.subtotal_cents||0),'Original rental subtotal'],['service_fee',Number(before.service_fee_cents||0),'Original service/platform fee'],['taxes',Number(before.taxes_cents||0),'Original taxes']] as const;
  for(const [category,amount,description] of components)if(amount>0)entries.push(entry({stable_key:`booking:${category}`,entry_type:'booking_component',category,amount_cents:amount,currency:before.currency||'usd',effect:'trip_debit',status:'posted',source:'zonyx_historical_snapshot',external_reference:null,description,occurred_at:before.created_at,metadata:{}}));
  const stripeTotal=snapshot.checkout?.amount_total;
  if(Number.isInteger(stripeTotal)&&stripeTotal!==oldTotal){const diff=stripeTotal-oldTotal;entries.push(entry({stable_key:`adjustment:stripe-checkout:${snapshot.checkout.id}`,entry_type:'adjustment',category:'historical_stripe_total_correction',amount_cents:Math.abs(diff),currency:snapshot.checkout.currency||'usd',effect:diff>=0?'trip_debit':'trip_credit',status:'posted',source:'stripe_checkout',external_reference:snapshot.checkout.id,description:'Adjustment from prior ZONYX total to Stripe-proven Checkout total',occurred_at:iso(snapshot.checkout.created,observed),metadata:{prior_local_total_cents:oldTotal,stripe_total_cents:stripeTotal}}));}
  const payment=snapshot.rental_payment;if(payment?.status==='succeeded'&&Number.isInteger(payment.amount_received))entries.push(entry({stable_key:`payment:${payment.payment_intent_id}`,entry_type:'payment',category:'rental_payment',amount_cents:payment.amount_received,currency:payment.currency||'usd',effect:'payment',status:'succeeded',source:'stripe_payment_intent',external_reference:payment.payment_intent_id,description:'Stripe-proven rental payment captured',occurred_at:iso(payment.created,observed),metadata:{charge_id:payment.latest_charge?.id||null}}));
  for(const refund of payment?.refunds||[])if(refund.status==='succeeded')entries.push(entry({stable_key:`refund:${refund.id}`,entry_type:'refund',category:'rental_refund',amount_cents:refund.amount,currency:refund.currency||'usd',effect:'refund',status:'succeeded',source:'stripe_refund',external_reference:refund.id,description:'Stripe-proven rental refund',occurred_at:iso(refund.created,observed),metadata:{payment_intent_id:payment.payment_intent_id}}));
  for(const attempt of snapshot.security_deposit_attempts?.timeline||[]){
    const include=attempt.association.confidence==='CONFIRMED'||(attempt.association.confidence==='AMBIGUOUS'&&approved.includes(attempt.payment_intent_id)); if(!include)continue;
    const meta={association_confidence:attempt.association.confidence,association_reasons:attempt.association.reasons,admin_approved_ambiguous:attempt.association.confidence==='AMBIGUOUS'};
    entries.push(entry({stable_key:`deposit-authorization:${attempt.payment_intent_id}`,entry_type:'deposit_authorization',category:'security_deposit',amount_cents:attempt.original_authorization,currency:attempt.currency||'usd',effect:'authorization',status:attempt.current_status||'unknown',source:'stripe_payment_intent',external_reference:attempt.payment_intent_id,description:'Security-deposit authorization attempt',occurred_at:iso(attempt.created,observed),metadata:meta}));
    const h=attempt.history;if(Number.isInteger(h.historical_captured_amount)&&h.historical_captured_amount>0)entries.push(entry({stable_key:`deposit-capture:${attempt.payment_intent_id}`,entry_type:'deposit_capture',category:'security_deposit',amount_cents:h.historical_captured_amount,currency:attempt.currency||'usd',effect:'deposit_capture',status:'succeeded',source:'stripe_evidence',external_reference:attempt.payment_intent_id,description:'Stripe-proven security-deposit capture',occurred_at:iso(attempt.created,observed),metadata:meta}));
    if(Number.isInteger(h.historical_released_uncaptured_amount))entries.push(entry({stable_key:`deposit-release:${attempt.payment_intent_id}`,entry_type:'deposit_release',category:'security_deposit',amount_cents:h.historical_released_uncaptured_amount,currency:attempt.currency||'usd',effect:'deposit_release',status:'settled',source:'stripe_evidence',external_reference:attempt.payment_intent_id,description:'Stripe-proven authorization released or uncaptured',occurred_at:iso(attempt.cancellation_timestamp||attempt.created,observed),metadata:meta}));
    if(Number.isInteger(h.historical_refunded_amount)&&h.historical_refunded_amount>0)entries.push(entry({stable_key:`deposit-refund:${attempt.payment_intent_id}`,entry_type:'deposit_refund',category:'security_deposit',amount_cents:h.historical_refunded_amount,currency:attempt.currency||'usd',effect:'deposit_refund',status:'succeeded',source:'stripe_refund',external_reference:attempt.payment_intent_id,description:'Stripe-proven refund of captured deposit funds',occurred_at:observed,metadata:meta}));
  }
  return {entries,excluded_ambiguous:(snapshot.security_deposit_attempts?.timeline||[]).filter((a:any)=>a.association.confidence==='AMBIGUOUS'&&!approved.includes(a.payment_intent_id)).map((a:any)=>a.payment_intent_id)};
}
export function summarizeEntries(entries:Entry[]){const sum=(effect:string)=>entries.filter(e=>e.effect===effect).reduce((s,e)=>s+e.amount_cents,0);const original=entries.filter(e=>e.entry_type==='booking_component'&&e.effect==='trip_debit').reduce((s,e)=>s+e.amount_cents,0);const debits=sum('trip_debit'),credits=sum('trip_credit'),paid=sum('payment'),refunds=sum('refund'),captured=sum('deposit_capture'),depositRefund=sum('deposit_refund');return{original_trip_amount_cents:original,adjustments_cents:debits-original-credits,final_trip_total_cents:debits-credits,amount_paid_cents:paid,refunds_cents:refunds,net_trip_payments_cents:paid-refunds,deposit_authorized_cents:Math.max(0,...entries.filter(e=>e.effect==='authorization').map(e=>e.amount_cents)),deposit_captured_cents:captured,deposit_released_cents:sum('deposit_release'),deposit_refunded_cents:depositRefund,net_deposit_retained_cents:captured-depositRefund,balance_cents:debits-credits-paid+refunds};}
export function proposalFingerprintPayload(entries:Entry[],approved:string[]){return JSON.stringify({approved:[...approved].sort(),entries:entries.map(e=>({stable_key:e.stable_key,amount_cents:e.amount_cents,effect:e.effect,status:e.status,external_reference:e.external_reference})).sort((a,b)=>a.stable_key.localeCompare(b.stable_key))});}