import { useState } from "react";
import { useQuery, useQueryClient } from "@tanstack/react-query";
import { supabase } from "@/integrations/supabase/client";
import { useToast } from "@/hooks/use-toast";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Checkbox } from "@/components/ui/checkbox";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";

const categories=[['tolls','Tolls'],['excess_mileage','Excess mileage'],['late_return','Late return'],['cleaning','Cleaning'],['damage','Damage-related charge'],['charging_energy','Charging / energy'],['parking_tickets_violations','Parking / tickets / violations'],['other','Other permitted charge']] as const;
const money=(cents:number)=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(cents/100);
type Charge={id:string;category:string;amount_cents:number;explanation:string;status:string;payment_status:string;submitted_at:string;evidence:{id:string;image_type:string;notes:string|null}[]};

export function AfterTripChargesPanel({bookingId,canSubmit=false,isAdmin=false}:{bookingId:string;canSubmit?:boolean;isAdmin?:boolean}){
 const{toast}=useToast();const qc=useQueryClient();const[category,setCategory]=useState('tolls');const[amount,setAmount]=useState('');const[explanation,setExplanation]=useState('');const[selectedEvidence,setSelectedEvidence]=useState<string[]>([]);const[working,setWorking]=useState(false);
 const{data:receipt}=useQuery({queryKey:['final-trip-receipt',bookingId],queryFn:async()=>{const{data,error}=await supabase.rpc('get_final_trip_receipt',{_booking_id:bookingId});if(error)throw error;return data as unknown as {after_trip_charges:Charge[]};},enabled:!!bookingId});
 const{data:evidence=[]}=useQuery({queryKey:['after-trip-evidence-options',bookingId],queryFn:async()=>{const{data,error}=await supabase.from('rental_images').select('id,image_type,notes,created_at').eq('booking_id',bookingId).order('created_at',{ascending:false});if(error)throw error;return data??[];},enabled:canSubmit});
 const submit=async()=>{const cents=Math.round(Number(amount)*100);if(!Number.isFinite(cents)||cents<=0||explanation.trim().length<5)return;setWorking(true);const key=`after-trip:${bookingId}:${crypto.randomUUID()}`;const{error}=await supabase.rpc('submit_after_trip_charge',{_booking_id:bookingId,_category:category,_amount_cents:cents,_explanation:explanation,_evidence_ids:selectedEvidence,_idempotency_key:key});setWorking(false);if(error)return toast({title:'Unable to submit charge',description:error.message,variant:'destructive'});setAmount('');setExplanation('');setSelectedEvidence([]);qc.invalidateQueries({queryKey:['final-trip-receipt',bookingId]});qc.invalidateQueries({queryKey:['booking-financial-summary',bookingId]});toast({title:'After-trip charge submitted',description:'This records an unpaid request. No payment was collected.'});};
 const adminStatus=async(id:string,status:'disputed'|'waived'|'voided')=>{const reason=window.prompt(`Reason to mark this charge ${status}:`);if(!reason||reason.trim().length<5)return;const{error}=await supabase.rpc('admin_set_after_trip_charge_status',{_charge_id:id,_new_status:status,_reason:reason});if(error)return toast({title:'Unable to update charge',description:error.message,variant:'destructive'});qc.invalidateQueries({queryKey:['final-trip-receipt',bookingId]});qc.invalidateQueries({queryKey:['booking-financial-summary',bookingId]});};
 return <Card><CardHeader><CardTitle className="text-base">After-Trip Charges</CardTitle><CardDescription>Submitted requests are unpaid until separate payment evidence exists. Security-deposit activity is tracked separately.</CardDescription></CardHeader><CardContent className="space-y-4">
  {(receipt?.after_trip_charges||[]).map(c=><div key={c.id} className="rounded-lg border p-3 text-sm"><div className="flex flex-wrap justify-between gap-2"><strong>{categories.find(x=>x[0]===c.category)?.[1]||c.category} · {money(c.amount_cents)}</strong><span className="uppercase text-muted-foreground">{c.status} · {c.payment_status}</span></div><p className="mt-1">{c.explanation}</p>{c.evidence?.length>0&&<p className="mt-1 text-xs text-muted-foreground">Evidence: {c.evidence.map(x=>x.image_type).join(', ')}</p>}{isAdmin&&!['paid','waived','voided'].includes(c.status)&&<div className="mt-2 flex gap-2"><Button size="sm" variant="outline" onClick={()=>adminStatus(c.id,'disputed')}>Disputed</Button><Button size="sm" variant="outline" onClick={()=>adminStatus(c.id,'waived')}>Waive</Button><Button size="sm" variant="outline" onClick={()=>adminStatus(c.id,'voided')}>Void</Button></div>}</div>)}
  {(receipt?.after_trip_charges||[]).length===0&&<p className="text-sm text-muted-foreground">No after-trip charges.</p>}
  {canSubmit&&<div className="space-y-3 border-t pt-4"><p className="font-semibold">Add after-trip charge</p><div><Label>Category</Label><select className="h-10 w-full rounded-md border border-input bg-background px-3 text-sm" value={category} onChange={e=>setCategory(e.target.value)}>{categories.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></div><div><Label>Amount (USD)</Label><Input type="number" min="0.01" step="0.01" value={amount} onChange={e=>setAmount(e.target.value)}/></div><div><Label>Explanation</Label><Textarea value={explanation} onChange={e=>setExplanation(e.target.value)} placeholder="Explain the permitted charge and supporting facts"/></div>{evidence.length>0&&<div><Label>Existing condition-photo evidence (optional)</Label>{evidence.map(x=><label key={x.id} className="mt-2 flex items-center gap-2 text-sm"><Checkbox checked={selectedEvidence.includes(x.id)} onCheckedChange={v=>setSelectedEvidence(v?[...selectedEvidence,x.id]:selectedEvidence.filter(id=>id!==x.id))}/>{x.image_type} photo{x.notes?` · ${x.notes}`:''}</label>)}</div>}<Button type="button" disabled={working||!amount||explanation.trim().length<5} onClick={submit}>{working?'Submitting…':'Submit unpaid charge request'}</Button></div>}
 </CardContent></Card>;
}