import { useQuery } from "@tanstack/react-query";
import { Link } from "react-router-dom";
import { supabase } from "@/integrations/supabase/client";
import { Card, CardContent } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { HistoricalAfterTripReconciliation } from "@/components/admin/HistoricalAfterTripReconciliation";
import { afterTripCategoryLabel } from "@/lib/afterTripSettlement";
import { groupAfterTripOperations, summarizeAfterTripOperations, type AfterTripOperationLine } from "@/lib/afterTripOperations";

type UnreconciledSource = { ledger_entry_id:string; booking_id:string; reservation_number:string; trip_status:string; vehicle:string; guest_name:string|null; guest_email:string; host_name:string|null; host_email:string; source_type:string; description:string; external_reference:string|null; amount_cents:number; allocated_cents:number; available_cents:number; currency:string; occurred_at:string };
const money=(value:number)=>new Intl.NumberFormat("en-US",{style:"currency",currency:"USD"}).format(value/100);

export function AdminAfterTripChargesTab(){
 const{data,isLoading}=useQuery({queryKey:["admin-after-trip-charges"],queryFn:async()=>{const{data,error}=await supabase.rpc("get_after_trip_operations",{_booking_id:null});if(error)throw error;return data as {charges?:AfterTripOperationLine[];unreconciled_sources?:UnreconciledSource[]};}});
 const trips=groupAfterTripOperations(data?.charges||[]);const unreconciled=data?.unreconciled_sources||[];const summary=summarizeAfterTripOperations(trips);
 if(isLoading)return <p>Loading after-trip charges…</p>;
 return <div className="space-y-4">
  <div className="grid gap-3 sm:grid-cols-3"><Card><CardContent className="p-4"><p className="text-xs uppercase text-muted-foreground">Trips with After-Trip Charges</p><p className="text-2xl font-bold">{summary.trip_count}</p></CardContent></Card><Card><CardContent className="p-4"><p className="text-xs uppercase text-muted-foreground">Total After-Trip Charges</p><p className="text-2xl font-bold">{money(summary.total_charge_cents)}</p></CardContent></Card><Card><CardContent className="p-4"><p className="text-xs uppercase text-muted-foreground">Outstanding</p><p className="text-2xl font-bold">{money(summary.outstanding_cents)}</p></CardContent></Card></div>
  {unreconciled.map(source=><Card key={source.ledger_entry_id} className="border-amber-500/60"><CardContent className="space-y-4 p-5"><div><p className="text-xs font-bold uppercase tracking-wide text-amber-600">Unreconciled proven settlement source</p><p className="mt-1 text-lg font-semibold">{source.reservation_number} · {source.vehicle}</p><p className="text-sm text-muted-foreground">Guest: {source.guest_name||source.guest_email} · Host: {source.host_name||source.host_email}</p></div><div className="grid gap-3 text-sm sm:grid-cols-5"><div><p className="text-muted-foreground">Proven deposit capture</p><p className="font-semibold">{money(source.amount_cents)}</p></div><div><p className="text-muted-foreground">Itemized After-Trip charges</p><p className="font-semibold">{money(0)} / missing</p></div><div><p className="text-muted-foreground">Allocated settlement</p><p className="font-semibold">{money(source.allocated_cents)}</p></div><div><p className="text-muted-foreground">Unallocated proven funds</p><p className="font-semibold">{money(source.available_cents)}</p></div><div><p className="text-muted-foreground">Status</p><p className="font-semibold uppercase text-amber-600">Unreconciled</p></div></div><p className="text-sm text-muted-foreground">No charge category is inferred. Enter only the actual documented charges below; this records ZONYX reconciliation data and does not charge Stripe again.</p><HistoricalAfterTripReconciliation bookingId={source.booking_id}/></CardContent></Card>)}
  {trips.map(trip=><Card key={trip.booking_id}><CardContent className="space-y-4 p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-lg font-semibold">{trip.reservation_number} · {trip.vehicle}</p><p className="text-sm text-muted-foreground">Guest: {trip.guest} · Host: {trip.host}</p><p className="mt-1 text-xs font-semibold uppercase tracking-wide text-muted-foreground">{trip.trip_status.replace(/_/g," ")}</p></div><Button asChild variant="outline" size="sm"><Link to={`/trip/${trip.booking_id}/receipt`}>Open receipt</Link></Button></div><div><p className="mb-2 font-semibold">After-Trip Charges</p><div className="space-y-2">{trip.charges.map(line=><div key={line.charge_id} className="border-t pt-2"><div className="flex justify-between gap-4 text-sm"><span>{afterTripCategoryLabel(line.category)}</span><strong>{money(line.amount_cents)}</strong></div><p className="text-xs text-muted-foreground">{line.explanation}</p><p className="text-xs text-muted-foreground">Settled {money(line.settled_amount_cents)} · Remaining {money(line.remaining_amount_cents)}</p></div>)}</div></div><div className="grid gap-3 border-t pt-3 text-sm sm:grid-cols-3"><div><p className="text-muted-foreground">Total charges</p><p className="font-semibold">{money(trip.total_charge_cents)}</p></div><div><p className="text-muted-foreground">Settled</p><p className="font-semibold">{money(trip.settled_cents)}</p></div><div><p className="text-muted-foreground">Outstanding</p><p className="font-semibold">{money(trip.outstanding_cents)}</p></div></div></CardContent></Card>)}
  {trips.length===0&&unreconciled.length===0&&<p className="text-sm text-muted-foreground">No after-trip charges or unreconciled proven settlement sources.</p>}
 </div>;
}