import { useMemo, useState } from "react";
import { supabase } from "@/integrations/supabase/client";
import { useToast } from "@/hooks/use-toast";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Checkbox } from "@/components/ui/checkbox";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { formatInspectorMoney } from "@/lib/financialInspector";

type Attempt={payment_intent_id:string;original_authorization:number;history:{historical_captured_amount:number|null;historical_released_uncaptured_amount:number|null};association:{confidence:string;reasons:string[]}};
type Preview={current_zonyx:{grand_total_cents:number;start_date:string;pickup_time:string|null;end_date:string;dropoff_time:string|null};stripe_evidence:{checkout_total_cents:number|null;rental_payment_received_cents:number|null};proposed_ledger:{stable_key:string;description:string;amount_cents:number;effect:string;external_reference:string|null}[];proposed_summary:{final_trip_total_cents:number;amount_paid_cents:number;deposit_captured_cents:number;deposit_released_cents:number;balance_cents:number};excluded_ambiguous:string[];proposal_fingerprint:string};

export function FinancialReconciliationPanel({bookingId,snapshot}:{bookingId:string;snapshot:any}){
  const{toast}=useToast();const[approved,setApproved]=useState<string[]>([]);const[preview,setPreview]=useState<Preview|null>(null);const[reason,setReason]=useState("");const[confirmed,setConfirmed]=useState(false);const[working,setWorking]=useState(false);
  const[startDate,setStartDate]=useState("");const[pickupTime,setPickupTime]=useState("");const[endDate,setEndDate]=useState("");const[dropoffTime,setDropoffTime]=useState("");const[scheduleReason,setScheduleReason]=useState("");
  const ambiguous=useMemo(()=>(snapshot.security_deposit_attempts?.timeline||[]).filter((x:Attempt)=>x.association.confidence==="AMBIGUOUS"),[snapshot]);
  const invoke=async(action:"prepare"|"confirm")=>{setWorking(true);const{data:session}=await supabase.auth.getSession();const token=session.session?.access_token;if(!token){setWorking(false);return toast({title:"Admin session required",variant:"destructive"});}const body:any={action,booking_id:bookingId,approved_ambiguous_payment_intent_ids:approved};if(action==="confirm"){body.reason=reason;body.idempotency_key=`reconcile:${bookingId}:${snapshot.observed_at}`;body.proposal_fingerprint=preview?.proposal_fingerprint||"";}const{data,error}=await supabase.functions.invoke("booking-financial-reconciliation",{headers:{Authorization:`Bearer ${token}`},body});setWorking(false);if(error)return toast({title:"Unable to reconcile",description:error.message,variant:"destructive"});if(action==="prepare"){setPreview(data.preview);setConfirmed(false);}else{toast({title:"Reconciliation recorded",description:"ZONYX ledger and audit history were updated. Stripe was not modified."});setPreview(null);}};
  const correctSchedule=async()=>{if(!startDate||!endDate||!pickupTime||!dropoffTime||scheduleReason.trim().length<5)return;const ok=window.confirm("Record this historical schedule correction? Pricing and financial ledger values will not change.");if(!ok)return;setWorking(true);const{error}=await supabase.rpc("admin_correct_historical_booking_schedule",{_booking_id:bookingId,_start_date:startDate,_pickup_time:pickupTime,_end_date:endDate,_dropoff_time:dropoffTime,_reason:scheduleReason});setWorking(false);toast(error?{title:"Unable to correct schedule",description:error.message,variant:"destructive"}:{title:"Historical schedule corrected",description:"Old/new values and reason were recorded. Financial totals were unchanged."});};
  return <Card className="border-primary/40"><CardHeader><CardTitle>Booking Financial Reconciliation</CardTitle><CardDescription>Preview first. Confirmation writes only an immutable ZONYX ledger and audit record; it never moves Stripe funds.</CardDescription></CardHeader><CardContent className="space-y-4">
    {ambiguous.length>0&&<div className="space-y-2"><p className="text-sm font-semibold">Ambiguous Stripe attempts</p>{ambiguous.map((a:Attempt)=><label key={a.payment_intent_id} className="flex items-start gap-2 rounded border p-3 text-sm"><Checkbox disabled={!!preview} checked={approved.includes(a.payment_intent_id)} onCheckedChange={(v)=>{setApproved(v?[...approved,a.payment_intent_id]:approved.filter(x=>x!==a.payment_intent_id));setPreview(null);}}/><span><strong>{a.payment_intent_id}</strong> — {formatInspectorMoney(a.original_authorization)} authorization; captured {formatInspectorMoney(a.history.historical_captured_amount)}, released {formatInspectorMoney(a.history.historical_released_uncaptured_amount)}.<br/><span className="text-muted-foreground">{a.association.reasons.join(", ").replace(/_/g," ")}. Selecting this records an Admin-approved ambiguous association.</span></span></label>)}</div>}
    <Button type="button" variant="outline" disabled={working} onClick={()=>invoke("prepare")}>{working?"Preparing…":"Prepare reconciliation"}</Button>
    {preview&&<div className="space-y-4 rounded-lg border p-4"><h3 className="font-semibold">Preview — no changes recorded yet</h3><div className="grid gap-3 text-sm sm:grid-cols-3"><div><p className="text-muted-foreground">Current ZONYX total</p><p>{formatInspectorMoney(preview.current_zonyx.grand_total_cents)}</p></div><div><p className="text-muted-foreground">Stripe checkout</p><p>{formatInspectorMoney(preview.stripe_evidence.checkout_total_cents)}</p></div><div><p className="text-muted-foreground">Stripe payment received</p><p>{formatInspectorMoney(preview.stripe_evidence.rental_payment_received_cents)}</p></div><div><p className="text-muted-foreground">Proposed final trip total</p><p>{formatInspectorMoney(preview.proposed_summary.final_trip_total_cents)}</p></div><div><p className="text-muted-foreground">Deposit captured / released</p><p>{formatInspectorMoney(preview.proposed_summary.deposit_captured_cents)} / {formatInspectorMoney(preview.proposed_summary.deposit_released_cents)}</p></div><div><p className="text-muted-foreground">Proposed balance</p><p>{formatInspectorMoney(preview.proposed_summary.balance_cents)}</p></div></div><div>{preview.proposed_ledger.map(e=><div key={e.stable_key} className="flex justify-between gap-4 border-t py-2 text-sm"><span>{e.description}<br/><span className="text-xs text-muted-foreground">{e.effect} · {e.external_reference||"ZONYX snapshot"}</span></span><strong>{formatInspectorMoney(e.amount_cents)}</strong></div>)}</div><div className="space-y-2"><Label htmlFor="reconciliation-reason">Reconciliation reason</Label><Input id="reconciliation-reason" value={reason} onChange={e=>setReason(e.target.value)} placeholder="Historical booking reconciliation from Stripe evidence"/><label className="flex items-center gap-2 text-sm"><Checkbox checked={confirmed} onCheckedChange={v=>setConfirmed(v===true)}/>I confirm this preview and any selected ambiguous associations belong to this booking.</label><Button type="button" disabled={working||!confirmed||reason.trim().length<5} onClick={()=>invoke("confirm")}>{working?"Recording…":"Confirm ZONYX reconciliation"}</Button></div></div>}
    <div className="space-y-3 border-t pt-4"><div><h3 className="font-semibold">Historical Schedule Correction</h3><p className="text-xs text-muted-foreground">Admin-only. Records old/new schedule and reason. Does not recalculate or change financial totals.</p></div><div className="grid gap-3 sm:grid-cols-2"><div><Label>Pickup date</Label><Input type="date" value={startDate} onChange={e=>setStartDate(e.target.value)}/></div><div><Label>Pickup time</Label><Input type="time" value={pickupTime} onChange={e=>setPickupTime(e.target.value)}/></div><div><Label>Drop-off date</Label><Input type="date" value={endDate} onChange={e=>setEndDate(e.target.value)}/></div><div><Label>Drop-off time</Label><Input type="time" value={dropoffTime} onChange={e=>setDropoffTime(e.target.value)}/></div></div><div><Label>Correction reason</Label><Input value={scheduleReason} onChange={e=>setScheduleReason(e.target.value)} placeholder="Evidence supporting this historical correction"/></div><Button type="button" variant="outline" disabled={working||!startDate||!pickupTime||!endDate||!dropoffTime||scheduleReason.trim().length<5} onClick={correctSchedule}>Record historical schedule correction</Button></div>
  </CardContent></Card>;
}