import { useMemo, useState } from "react";
import { useQuery, useQueryClient } from "@tanstack/react-query";
import { supabase } from "@/integrations/supabase/client";
import { afterTripCategories, afterTripCategoryLabel, totalHistoricalCharges, type HistoricalChargeLine } from "@/lib/afterTripSettlement";
import { useToast } from "@/hooks/use-toast";
import { Button } from "@/components/ui/button";
import { Checkbox } from "@/components/ui/checkbox";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";

type Source={id:string;effect:"deposit_capture"|"payment";category:string;amount_cents:number;currency:string;external_reference:string|null;description:string};
type Preview={charges:(HistoricalChargeLine&{ordinal:number})[];total_charge_cents:number;settlement_source:string;source_amount_cents:number;source_already_allocated_cents:number;source_available_cents:number;proposed_settlement_cents:number;additional_balance_due_cents:number;proposal_fingerprint:string;writes_performed:false};
const money=(cents:number)=>new Intl.NumberFormat("en-US",{style:"currency",currency:"USD"}).format((cents||0)/100);
const emptyLine=():HistoricalChargeLine=>({category:"charging_energy",amount_cents:0,explanation:""});

export function HistoricalAfterTripReconciliation({bookingId}:{bookingId:string}){
 const{toast}=useToast();const qc=useQueryClient();const[lines,setLines]=useState<HistoricalChargeLine[]>([emptyLine()]);const[sourceId,setSourceId]=useState("");const[preview,setPreview]=useState<Preview|null>(null);const[reason,setReason]=useState("");const[confirmed,setConfirmed]=useState(false);const[working,setWorking]=useState(false);
 const{data:sources=[]}=useQuery({queryKey:["after-trip-settlement-sources",bookingId],queryFn:async()=>{const{data,error}=await supabase.from("booking_financial_ledger").select("id,effect,category,amount_cents,currency,external_reference,description").eq("booking_id",bookingId).eq("status","succeeded").in("effect",["deposit_capture","payment"]).order("occurred_at");if(error)throw error;return((data??[]) as Source[]).filter(s=>s.effect==="deposit_capture"||s.category==="after_trip_payment");}});
 const total=useMemo(()=>totalHistoricalCharges(lines),[lines]);
 const payload=()=>lines.map(x=>({category:x.category,amount_cents:x.amount_cents,explanation:x.explanation.trim()}));
 const prepare=async()=>{if(!sourceId||lines.some(x=>x.amount_cents<=0||x.explanation.trim().length<5))return;setWorking(true);const{data,error}=await supabase.rpc("prepare_historical_after_trip_reconciliation",{_booking_id:bookingId,_charges:payload() as any,_source_ledger_entry_id:sourceId});setWorking(false);if(error)return toast({title:"Unable to prepare reconciliation",description:error.message,variant:"destructive"});setPreview(data as unknown as Preview);setConfirmed(false);};
 const confirm=async()=>{if(!preview||!confirmed||reason.trim().length<5)return;setWorking(true);const{error}=await supabase.rpc("confirm_historical_after_trip_reconciliation",{_booking_id:bookingId,_charges:payload() as any,_source_ledger_entry_id:sourceId,_reason:reason.trim(),_idempotency_key:`historical-after-trip:${bookingId}:${preview.proposal_fingerprint}`,_proposal_fingerprint:preview.proposal_fingerprint});setWorking(false);if(error)return toast({title:"Unable to record reconciliation",description:error.message,variant:"destructive"});setPreview(null);setReason("");setConfirmed(false);qc.invalidateQueries({queryKey:["final-trip-receipt",bookingId]});qc.invalidateQueries({queryKey:["booking-financial-summary",bookingId]});qc.invalidateQueries({queryKey:["admin-after-trip-charges"]});toast({title:"Historical after-trip reconciliation recorded",description:"ZONYX records were updated. Stripe was not modified."});};
 const update=(i:number,patch:Partial<HistoricalChargeLine>)=>{setLines(v=>v.map((x,n)=>n===i?{...x,...patch}:x));setPreview(null)};
 return <div className="space-y-4 rounded-lg border border-primary/40 p-4"><div><h3 className="font-semibold uppercase tracking-wide">Historical After-Trip Reconciliation</h3><p className="text-sm text-muted-foreground">Records historical charge lines against existing proven ledger evidence. Previewing and confirming never moves Stripe funds.</p></div>
  {lines.map((line,i)=><div key={i} className="grid gap-2 rounded border p-3 sm:grid-cols-[1fr_140px_2fr_auto]"><select className="h-10 rounded-md border bg-background px-2 text-sm" value={line.category} onChange={e=>update(i,{category:e.target.value})}>{afterTripCategories.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select><Input type="number" min="0.01" step="0.01" value={line.amount_cents?line.amount_cents/100:""} placeholder="0.00" onChange={e=>update(i,{amount_cents:Math.round(Number(e.target.value)*100)})}/><Input value={line.explanation} placeholder="Evidence-based explanation" onChange={e=>update(i,{explanation:e.target.value})}/><Button type="button" variant="ghost" disabled={lines.length===1} onClick={()=>{setLines(v=>v.filter((_,n)=>n!==i));setPreview(null)}}>Remove</Button></div>)}
  <div className="flex flex-wrap items-center justify-between gap-2"><Button type="button" variant="outline" onClick={()=>{setLines(v=>[...v,emptyLine()]);setPreview(null)}}>Add charge line</Button><strong>Running total: {money(total)}</strong></div>
  <div><Label>Proven settlement source</Label><select className="h-10 w-full rounded-md border bg-background px-3 text-sm" value={sourceId} onChange={e=>{setSourceId(e.target.value);setPreview(null)}}><option value="">Select immutable payment evidence</option>{sources.map(s=><option key={s.id} value={s.id}>{s.effect==="deposit_capture"?"Security deposit capture":"Separate payment"} · {money(s.amount_cents)} · {s.external_reference||s.description}</option>)}</select></div>
  <Button type="button" variant="outline" disabled={working||!sourceId||total<=0||lines.some(x=>x.explanation.trim().length<5)} onClick={prepare}>{working?"Preparing…":"Prepare historical reconciliation"}</Button>
  {preview&&<div className="space-y-3 rounded-lg border bg-muted/20 p-4"><h4 className="font-semibold">Preview — no records written yet</h4>{preview.charges.map(x=><div key={x.ordinal} className="flex justify-between text-sm"><span>{afterTripCategoryLabel(x.category)}</span><span>{money(x.amount_cents)}</span></div>)}<div className="space-y-1 border-t pt-2 text-sm"><div className="flex justify-between font-semibold"><span>Total charges</span><span>{money(preview.total_charge_cents)}</span></div><div className="flex justify-between"><span>Paid from {preview.settlement_source.replace(/_/g," ")}</span><span>{money(preview.proposed_settlement_cents)}</span></div><div className="flex justify-between"><span>Additional balance due</span><span>{money(preview.additional_balance_due_cents)}</span></div></div><div><Label>Reconciliation reason</Label><Textarea value={reason} onChange={e=>setReason(e.target.value)} placeholder="Historical after-trip reconciliation from documented evidence"/></div><label className="flex items-start gap-2 text-sm"><Checkbox checked={confirmed} onCheckedChange={v=>setConfirmed(v===true)}/>I confirm these historical charges belong to this booking and the selected immutable ledger source proves the stated settlement.</label><Button type="button" disabled={working||!confirmed||reason.trim().length<5} onClick={confirm}>Confirm ZONYX records only</Button></div>}
 </div>;
}