import { useEffect, useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { AlertDialog, AlertDialogAction, AlertDialogCancel, AlertDialogContent, AlertDialogDescription, AlertDialogFooter, AlertDialogHeader, AlertDialogTitle } from "@/components/ui/alert-dialog";
import { Badge } from "@/components/ui/badge";
import { supabase } from "@/integrations/supabase/client";
import { useToast } from "@/hooks/use-toast";

type Plan={id:string;status:string;original_end_date:string;original_dropoff_time:string;extended_through_date:string;extended_dropoff_time:string;monthly_amount_cents:number;currency:string;communication_enabled:boolean;reason:string;created_at:string;activated_at:string|null;activated_revision_id:string|null};
type Period={id:string;extension_plan_id:string;period_number:number;period_start:string;period_end:string;amount_due_cents:number;currency:string;billing_reminder_date:string;payment_status:string;notification_status:string;communication_enabled:boolean;display_status:"scheduled"|"reminder_due"|"payment_due"|"paid"|"active"|"completed";stripe_payment_intent_id:string|null;paid_at:string|null;reminder_sent_at:string|null};
type Schedule={booking_id:string;reservation_number:string;current_scheduled_return_date:string;current_scheduled_return_time:string;plans:Plan[];periods:Period[]};
type Props={bookingId:string|null;open:boolean;onOpenChange:(open:boolean)=>void};
const money=(cents:number,currency="usd")=>new Intl.NumberFormat("en-US",{style:"currency",currency:currency.toUpperCase()}).format(cents/100);
const label=(value:string)=>value.replaceAll("_"," ").replace(/\b\w/g,character=>character.toUpperCase());

export function RentalExtensionDialog({bookingId,open,onOpenChange}:Props){
 const{toast}=useToast();const queryClient=useQueryClient();const[extendedThrough,setExtendedThrough]=useState("");const[returnTime,setReturnTime]=useState("");const[amount,setAmount]=useState("");const[reason,setReason]=useState("");const[communicationEnabled,setCommunicationEnabled]=useState(false);const[pendingAction,setPendingAction]=useState<null|{kind:"activate";planId:string}|{kind:"payment"|"reminder";periodId:string}>(null);
 const{data,isLoading}=useQuery({queryKey:["rental-extension-schedule",bookingId],queryFn:async()=>{const{data,error}=await supabase.rpc("get_rental_extension_schedule",{_booking_id:bookingId!});if(error)throw error;return data as unknown as Schedule;},enabled:open&&Boolean(bookingId)});
 useEffect(()=>{if(!open||!data)return;setReturnTime(String(data.current_scheduled_return_time||"").slice(0,5));setCommunicationEnabled(false);},[open,data]);
 const refresh=()=>{queryClient.invalidateQueries({queryKey:["rental-extension-schedule",bookingId]});queryClient.invalidateQueries({queryKey:["host-bookings"]});queryClient.invalidateQueries({queryKey:["booking-rental-agreement",bookingId]});queryClient.invalidateQueries({queryKey:["rental-agreement-history",bookingId]});};
 const scheduleMutation=useMutation({mutationFn:async()=>{const cents=Math.round(Number(amount)*100);const{data,error}=await supabase.rpc("admin_schedule_rental_extension",{_booking_id:bookingId!,_extended_through_date:extendedThrough,_extended_dropoff_time:returnTime,_monthly_amount_cents:cents,_communication_enabled:communicationEnabled,_reason:reason.trim()});if(error)throw error;return data;},onSuccess:()=>{refresh();setExtendedThrough("");setAmount("");setReason("");setCommunicationEnabled(false);toast({title:"Extension schedule created",description:"The booking and Current Operative Agreement were not changed. No payment or Guest communication occurred."});},onError:error=>toast({title:"Unable to schedule extension",description:error.message,variant:"destructive"})});
 const activateMutation=useMutation({mutationFn:async(planId:string)=>{const{data,error}=await supabase.rpc("admin_activate_rental_extension",{_plan_id:planId});if(error)throw error;return data;},onSuccess:()=>{refresh();toast({title:"Rental extension activated",description:"The existing booking and Current Operative Agreement were updated. No payment or Guest communication occurred."});},onError:error=>toast({title:"Unable to activate extension",description:error.message,variant:"destructive"})});
 const externalMutation=useMutation({mutationFn:async(payload:{kind:"payment"|"reminder";periodId:string})=>{const{data,error}=await supabase.functions.invoke("rental-extension-actions",{body:{action:payload.kind==="payment"?"initiatePayment":"sendReminder",periodId:payload.periodId}});if(error)throw new Error((error as{context?:{error?:string}}).context?.error||error.message);if(data?.error)throw new Error(data.error);return data;},onSuccess:(_,payload)=>{refresh();toast({title:payload.kind==="payment"?"Renewal payment action completed":"Renewal reminder sent"});},onError:error=>toast({title:"External action failed",description:error.message,variant:"destructive"})});
 const scheduledPlan=data?.plans.find(plan=>plan.status==="scheduled");
 const activePlan=[...(data?.plans??[])].reverse().find(plan=>plan.status==="active");
 const confirm=()=>{if(!pendingAction)return;if(pendingAction.kind==="activate")activateMutation.mutate(pendingAction.planId);else externalMutation.mutate(pendingAction);setPendingAction(null);};
 return <><Dialog open={open} onOpenChange={next=>{if(!next){setCommunicationEnabled(false);setPendingAction(null);}onOpenChange(next);}}><DialogContent className="max-h-[92vh] max-w-4xl overflow-y-auto"><DialogHeader><DialogTitle>Extend Rental</DialogTitle><DialogDescription>Schedule future periods on the existing booking. Scheduling alone does not activate an extension, contact the Guest, or perform a payment.</DialogDescription></DialogHeader>{isLoading?<p>Loading…</p>:<div className="space-y-5">
  <section className="rounded-lg border p-4"><p className="text-sm text-muted-foreground">Current scheduled return</p><p className="font-semibold">{data?.current_scheduled_return_date} at {String(data?.current_scheduled_return_time||"").slice(0,5)}</p>{scheduledPlan?<p className="mt-2 text-sm">Pending extension through: <strong>{scheduledPlan.extended_through_date} at {String(scheduledPlan.extended_dropoff_time).slice(0,5)}</strong> · Scheduled</p>:activePlan&&<p className="mt-2 text-sm">Active extension plan through: <strong>{activePlan.extended_through_date} at {String(activePlan.extended_dropoff_time).slice(0,5)}</strong></p>}</section>
  {!scheduledPlan&&<section className="space-y-4 rounded-lg border p-4"><h3 className="font-semibold">Schedule an extension</h3><div className="grid gap-4 sm:grid-cols-3"><div className="space-y-2"><Label>Extended-through date</Label><Input type="date" value={extendedThrough} onChange={event=>setExtendedThrough(event.target.value)}/></div><div className="space-y-2"><Label>Return time</Label><Input type="time" value={returnTime} onChange={event=>setReturnTime(event.target.value)}/></div><div className="space-y-2"><Label>Amount due per period (USD)</Label><Input type="number" min="0.50" step="0.01" value={amount} onChange={event=>setAmount(event.target.value)}/></div></div><div className="space-y-2"><Label>Reason</Label><Textarea value={reason} onChange={event=>setReason(event.target.value)} placeholder="Required extension reason"/></div><label className="flex items-start gap-2 rounded-md border p-3 text-sm"><input type="checkbox" checked={communicationEnabled} onChange={event=>setCommunicationEnabled(event.target.checked)}/><span><strong>Enable Guest renewal reminders for these periods</strong><br/><span className="text-muted-foreground">Defaults to off. Enabling permits a later explicit Send Reminder action; scheduling still sends nothing.</span></span></label><Button onClick={()=>scheduleMutation.mutate()} disabled={scheduleMutation.isPending||!extendedThrough||!returnTime||!Number.isFinite(Number(amount))||Number(amount)<=0||reason.trim().length<5}>{scheduleMutation.isPending?"Scheduling…":"Schedule extension periods"}</Button></section>}
  {scheduledPlan&&<section className="rounded-lg border border-amber-500/60 bg-amber-500/10 p-4"><p className="font-semibold">Scheduled — not yet operative</p><p className="text-sm">Activation updates the same booking return date and creates an immutable Current Operative Agreement revision. It sends no communication and performs no payment.</p><Button className="mt-3" onClick={()=>setPendingAction({kind:"activate",planId:scheduledPlan.id})}>Activate Extension</Button></section>}
  <section><h3 className="mb-3 font-semibold">Renewal / Extension Schedule</h3>{data?.periods.length?<div className="space-y-3">{data.periods.map(period=><div key={period.id} className="rounded-lg border p-4"><div className="flex flex-wrap items-start justify-between gap-2"><div><p className="font-semibold">Period {period.period_number}: {period.period_start} → {period.period_end}</p><p className="text-sm text-muted-foreground">Amount due: {money(period.amount_due_cents,period.currency)} · Billing/reminder date: {period.billing_reminder_date}</p></div><Badge>{label(period.display_status)}</Badge></div><div className="mt-3 flex flex-wrap gap-2 text-sm"><span>Payment: {label(period.payment_status)}</span><span>Reminder: {label(period.notification_status)}</span></div><div className="mt-3 flex flex-wrap gap-2">{period.payment_status!=="paid"&&<Button size="sm" variant="outline" onClick={()=>setPendingAction({kind:"payment",periodId:period.id})}>Initiate Renewal Payment</Button>}{period.communication_enabled&&period.notification_status!=="sent"&&<Button size="sm" variant="outline" onClick={()=>setPendingAction({kind:"reminder",periodId:period.id})}>Send Reminder</Button>}</div></div>)}</div>:<p className="text-sm text-muted-foreground">No extension periods scheduled.</p>}</section>
 </div>}<DialogFooter><Button variant="outline" onClick={()=>onOpenChange(false)}>Close</Button></DialogFooter></DialogContent></Dialog>
 <AlertDialog open={Boolean(pendingAction)} onOpenChange={next=>!next&&setPendingAction(null)}><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>{pendingAction?.kind==="activate"?"Activate this rental extension?":pendingAction?.kind==="payment"?"Initiate this renewal payment?":"Send this renewal reminder?"}</AlertDialogTitle><AlertDialogDescription>{pendingAction?.kind==="activate"?"This updates the existing booking return date and Current Operative Agreement. It does not contact or charge the Guest.":pendingAction?.kind==="payment"?"This is an explicit financial action for exactly one renewal period. Stripe idempotency prevents duplicate PaymentIntents on retry.":"This is an explicit customer-facing communication to the Guest for exactly one renewal period."}</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel>Cancel</AlertDialogCancel><AlertDialogAction onClick={confirm}>Confirm explicit action</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>
 </>;
}