import { useMemo, useState } from "react";
import { useQuery } from "@tanstack/react-query";
import { Link } from "react-router-dom";
import { Car, ClipboardList, Receipt, Users } from "lucide-react";
import { MainLayout } from "@/components/layout/MainLayout";
import { AccountModeGuard } from "@/components/account/AccountModeGuard";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { supabase } from "@/integrations/supabase/client";
import { afterTripCategoryLabel } from "@/lib/afterTripSettlement";
import { useAccountMode } from "@/contexts/AccountModeContext";

const money=(value:number,currency='usd')=>new Intl.NumberFormat('en-US',{style:'currency',currency:currency.toUpperCase()}).format(Number(value||0)/100);
const label=(value:string|null|undefined)=>value?value.replace(/_/g,' '):'Not recorded';
type OpsBooking={booking_id:string;reservation_number:string;trip_status:string;start_date:string;pickup_time:string|null;end_date:string;dropoff_time:string|null;pickup_location:string|null;dropoff_location:string|null;fulfillment_method:string|null;vehicle:string;vehicle_image_url:string|null;guest_name:string;guest_email:string;host_name:string;host_email:string;currency:string;financial_reconciled:boolean;trip_total_cents:number;paid_cents:number;refunded_cents:number;balance_cents:number;receipt_available:boolean;deposit_authorized_cents:number;deposit_captured_cents:number;deposit_released_cents:number;deposit_refunded_cents:number;deposit_status:string;after_trip_charge_cents:number;after_trip_settled_cents:number;after_trip_outstanding_cents:number;after_trip_status:string};
type OpsVehicle={vehicle_id:string;vehicle_identifier:string;year:number;brand:string;model:string;category:string;color:string;location:string;image_url:string|null;is_active:boolean;availability_status:string;display_order:number|null;host_name:string;host_email:string;created_at:string;updated_at:string};
type OpsAccount={profile_id:string;full_name:string;email:string;is_guest:boolean;is_host:boolean;created_at:string};
type OpsTrip={booking_id:string;reservation_number:string;trip_status:string;vehicle:string;guest_name:string;guest_email:string;host_name:string;host_email:string;currency:string;total_charge_cents:number;settled_cents:number;outstanding_cents:number;settlement_status:string;charges:{charge_id:string;category:string;amount_cents:number;explanation:string;charge_status:string;settled_amount_cents:number;remaining_amount_cents:number;submitted_at:string;evidence:{image_type:string;notes:string|null;created_at:string}[]}[]};

function useOperationsRpc<T>(name:'get_operations_bookings'|'get_operations_vehicles'|'get_operations_accounts'|'get_operations_after_trip_queue',enabled:boolean){
 return useQuery({queryKey:[name],queryFn:async()=>{const{data,error}=await supabase.rpc(name);if(error)throw error;return (data??[]) as unknown as T[];},enabled});
}

export default function OperationsDashboard(){const{allowedModes}=useAccountMode();const enabled=allowedModes.includes('operations');const[query,setQuery]=useState('');const bookings=useOperationsRpc<OpsBooking>('get_operations_bookings',enabled);const vehicles=useOperationsRpc<OpsVehicle>('get_operations_vehicles',enabled);const accounts=useOperationsRpc<OpsAccount>('get_operations_accounts',enabled);const afterTrip=useOperationsRpc<OpsTrip>('get_operations_after_trip_queue',enabled);const q=query.trim().toLowerCase();const filter=<T,>(rows:T[],text:(row:T)=>string)=>q?rows.filter(row=>text(row).toLowerCase().includes(q)):rows;
 const bookingRows=useMemo(()=>filter(bookings.data??[],b=>`${b.reservation_number} ${b.vehicle} ${b.guest_name} ${b.guest_email} ${b.host_name} ${b.host_email} ${b.trip_status}`),[bookings.data,q]);
 const vehicleRows=useMemo(()=>filter(vehicles.data??[],v=>`${v.vehicle_identifier} ${v.year} ${v.brand} ${v.model} ${v.host_name} ${v.host_email} ${v.availability_status}`),[vehicles.data,q]);
 const accountRows=useMemo(()=>filter(accounts.data??[],a=>`${a.full_name} ${a.email} ${a.is_host?'host':'guest'}`),[accounts.data,q]);
 const tripRows=useMemo(()=>filter(afterTrip.data??[],t=>`${t.reservation_number} ${t.vehicle} ${t.guest_name} ${t.guest_email} ${t.host_name} ${t.host_email}`),[afterTrip.data,q]);
 return <AccountModeGuard mode="operations"><MainLayout><div className="container min-h-screen space-y-6 px-4 pb-16 pt-28"><div className="text-center"><p className="text-xs font-semibold uppercase tracking-[.3em] text-primary">Read-only platform operations</p><h1 className="mt-2 font-display text-3xl md:text-4xl">ZONYX OPERATIONS</h1><p className="mt-2 text-sm text-muted-foreground">Operational visibility without financial authority or mutation access.</p></div><Input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search reservation, Guest, Host, vehicle, or status" aria-label="Search Operations workspace"/><Tabs defaultValue="bookings" className="space-y-4"><TabsList className="grid w-full grid-cols-4"><TabsTrigger value="bookings"><ClipboardList className="mr-1 h-4 w-4"/><span className="hidden sm:inline">Bookings</span></TabsTrigger><TabsTrigger value="vehicles"><Car className="mr-1 h-4 w-4"/><span className="hidden sm:inline">Vehicles</span></TabsTrigger><TabsTrigger value="accounts"><Users className="mr-1 h-4 w-4"/><span className="hidden sm:inline">Accounts</span></TabsTrigger><TabsTrigger value="after-trip"><Receipt className="mr-1 h-4 w-4"/><span className="hidden sm:inline">After-Trip</span></TabsTrigger></TabsList>
 <TabsContent value="bookings" className="space-y-3">{bookingRows.map(b=><Card key={b.booking_id}><CardHeader><div className="flex flex-wrap items-center justify-between gap-2"><CardTitle className="text-base">{b.reservation_number} · {b.vehicle}</CardTitle><Badge>{label(b.trip_status)}</Badge></div></CardHeader><CardContent className="grid gap-3 text-sm sm:grid-cols-2 lg:grid-cols-4"><div><b>Guest</b><p>{b.guest_name||b.guest_email}</p></div><div><b>Host / provider</b><p>{b.host_name||b.host_email}</p></div><div><b>Schedule</b><p>{b.start_date} {b.pickup_time?.slice(0,5)} → {b.end_date} {b.dropoff_time?.slice(0,5)}</p></div><div><b>Fulfillment</b><p>{label(b.fulfillment_method)} · {b.pickup_location||'Not recorded'} → {b.dropoff_location||'Not recorded'}</p></div><div><b>Financial summary</b>{b.financial_reconciled?<p>Total {money(b.trip_total_cents,b.currency)} · Paid {money(b.paid_cents,b.currency)} · Refunded {money(b.refunded_cents,b.currency)} · Balance {money(b.balance_cents,b.currency)}</p>:<p>Total recorded {money(b.trip_total_cents,b.currency)} · Payment status not reconciled</p>}</div><div><b>Security deposit</b><p>{b.financial_reconciled?`${label(b.deposit_status)} · Authorized ${money(b.deposit_authorized_cents,b.currency)} · Captured ${money(b.deposit_captured_cents,b.currency)} · Released ${money(b.deposit_released_cents,b.currency)}`:"Not reconciled"}</p></div><div><b>After-trip settlement</b><p>{label(b.after_trip_status)} · Charges {money(b.after_trip_charge_cents,b.currency)} · Outstanding {money(b.after_trip_outstanding_cents,b.currency)}</p></div>{b.receipt_available&&<div className="flex items-end"><Button asChild variant="outline" size="sm"><Link to={`/operations/trip/${b.booking_id}/receipt`}>Open receipt</Link></Button></div>}</CardContent></Card>)}{!bookingRows.length&&<p className="text-sm text-muted-foreground">No matching bookings.</p>}</TabsContent>
 <TabsContent value="vehicles" className="grid gap-3 sm:grid-cols-2">{vehicleRows.map(v=><Card key={v.vehicle_id}><CardContent className="flex gap-3 p-4">{v.image_url&&<img src={v.image_url} alt="" className="h-20 w-28 rounded object-cover"/>}<div><p className="font-semibold">{v.year} {v.brand} {v.model}</p><p className="text-sm text-muted-foreground">{v.vehicle_identifier} · {v.location}</p><p className="text-sm">Provider: {v.host_name||v.host_email}</p><p className="text-sm capitalize">{v.is_active?'Active':'Inactive'} · {label(v.availability_status)}</p></div></CardContent></Card>)}</TabsContent>
 <TabsContent value="accounts" className="grid gap-3 sm:grid-cols-2">{accountRows.map(a=><Card key={a.profile_id}><CardContent className="p-4"><p className="font-semibold">{a.full_name||'Profile incomplete'}</p><p className="text-sm text-muted-foreground">{a.email}</p><p className="mt-2 text-xs uppercase tracking-wide">Guest{a.is_host?' · Host':''}</p><p className="text-xs text-muted-foreground">Created {new Date(a.created_at).toLocaleString()}</p></CardContent></Card>)}</TabsContent>
 <TabsContent value="after-trip" className="space-y-3">{tripRows.map(t=><Card key={t.booking_id}><CardHeader><div className="flex flex-wrap items-center justify-between gap-2"><CardTitle className="text-base">{t.reservation_number} · {t.vehicle}</CardTitle><Badge>{label(t.settlement_status)}</Badge></div></CardHeader><CardContent className="space-y-3 text-sm"><p>Guest: {t.guest_name||t.guest_email} · Host: {t.host_name||t.host_email} · {label(t.trip_status)}</p>{t.charges.map(c=><div key={c.charge_id} className="border-t pt-2"><div className="flex justify-between gap-3"><b>{afterTripCategoryLabel(c.category)}</b><span>{money(c.amount_cents,t.currency)}</span></div><p>{c.explanation}</p><p className="text-xs text-muted-foreground">{label(c.charge_status)} · Settled {money(c.settled_amount_cents,t.currency)} · Remaining {money(c.remaining_amount_cents,t.currency)}</p>{c.evidence?.map((e,i)=><p key={i} className="text-xs text-muted-foreground">Evidence: {label(e.image_type)}{e.notes?` · ${e.notes}`:''}</p>)}</div>)}<div className="grid gap-2 border-t pt-3 font-medium sm:grid-cols-3"><span>Total {money(t.total_charge_cents,t.currency)}</span><span>Settled {money(t.settled_cents,t.currency)}</span><span>Outstanding {money(t.outstanding_cents,t.currency)}</span></div><Button asChild variant="outline" size="sm"><Link to={`/operations/trip/${t.booking_id}/receipt`}>Open receipt</Link></Button></CardContent></Card>)}</TabsContent>
 </Tabs></div></MainLayout></AccountModeGuard>;
}